name: Lint GH Workflows
on:
  push:
jobs:
  lint_workflows:
    name: Validate Github Action Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Collect Metrics
        id: collect-gha-metrics
        uses: smartcontractkit/push-gha-metrics-action@v1
        with:
          basic-auth: ${{ secrets.GRAFANA_CLOUD_BASIC_AUTH }}
          hostname: ${{ secrets.GRAFANA_CLOUD_HOST }}
          this-job-name: Validate Github Action Workflows
        continue-on-error: true
      - name: Check out Code
        uses: actions/checkout@v3
      - name: Run actionlint
        uses: reviewdog/action-actionlint@8c8d2690df01d64638691b59cb1c37d913e6264f # v1.23.0
